// SPDX-License-Identifier: AGPL-3.0-only
// Copyright (C) 2026 Stefan Kovalik / Aurochs Digital

/**
 * TerminalPanel.tsx — Renderer-side xterm.js terminal component for artboard mode.
 *
 * Mounts an xterm.js Terminal instance, connects to the main-process PTY via the
 * preload IPC bridge (window.api.terminal), and handles:
 *   - Scrollback replay on mount
 *   - Keystroke forwarding to PTY
 *   - PTY output rendering
 *   - Debounced resize (150ms) via @xterm/addon-fit
 *   - PTY exit display
 *   - Ctrl+` focus escape to return to canvas
 *   - Dynamic light/dark theme sync via workspaceStore
 *
 * Session lifecycle: On unmount the component detaches listeners but does NOT kill
 * the PTY session, so the terminal persists across artboard toggles.
 */

import { useEffect, useRef, useCallback, useState, memo } from 'react'
import { Terminal } from '@xterm/xterm'
import { FitAddon } from '@xterm/addon-fit'
import { Unicode11Addon } from '@xterm/addon-unicode11'
import { WebglAddon } from '@xterm/addon-webgl'
import '@xterm/xterm/css/xterm.css'
import { useWorkspaceStore } from '../../stores/workspaceStore'
import { getTerminalTheme, TERMINAL_TOOLTIP_COLOR } from '../../constants/terminalThemes'

// ---------------------------------------------------------------------------
// Props
// ---------------------------------------------------------------------------

export interface TerminalPanelProps {
  /** Canvas node ID that owns this terminal session. */
  nodeId: string
  /** Unique session identifier (generated by caller). */
  sessionId: string
  /** Which shell to run. Defaults to 'claude-code'. */
  shell?: string
  /** Optional accent color override (CSS color string). Applied as cursor color. */
  accentColor?: string
  /** Additional CSS class names for the container div. */
  className?: string
  /** Node title for Claude Code context injection. */
  nodeTitle?: string
  /** Working directory for the terminal. */
  cwd?: string
}

// ---------------------------------------------------------------------------
// Constants
// ---------------------------------------------------------------------------

const RESIZE_DEBOUNCE_MS = 150

// ---------------------------------------------------------------------------
// Component
// Note: preview tee is handled by App.tsx onDataGlobal — do NOT duplicate here
// ---------------------------------------------------------------------------

/**
 * TerminalPanel renders an xterm.js terminal connected to a main-process PTY.
 *
 * Mount sequence:
 * 1. Create Terminal + FitAddon instances
 * 2. Open terminal into the container div
 * 3. Spawn PTY via IPC (or reconnect to existing session)
 * 4. Replay scrollback buffer
 * 5. Attach fit addon and perform initial fit
 * 6. Wire up data/exit/resize listeners
 *
 * Unmount: Dispose terminal + addon, remove IPC listeners. PTY stays alive.
 */
function TerminalPanelInner({
  nodeId,
  sessionId,
  shell,
  accentColor,
  className,
  nodeTitle,
  cwd,
}: TerminalPanelProps): JSX.Element {
  const containerRef = useRef<HTMLDivElement>(null)
  const terminalRef = useRef<Terminal | null>(null)
  const fitAddonRef = useRef<FitAddon | null>(null)
  const resizeTimerRef = useRef<ReturnType<typeof setTimeout> | null>(null)
  const mountedRef = useRef(true)
  const isReplayingRef = useRef(true)          // true during scrollback replay — buffers incoming data
  const pendingDataRef = useRef<string[]>([])   // data buffered during scrollback replay, flushed after
  const [processExited, setProcessExited] = useState(false)
  /** Incremented to force the main effect to re-run on respawn. */
  const [spawnGeneration, setSpawnGeneration] = useState(0)

  // Subscribe to theme mode for dynamic theme switching
  const themeMode = useWorkspaceStore((state) => state.themeSettings.mode)
  const workspaceId = useWorkspaceStore((state) => state.workspaceId)

  // -------------------------------------------------------------------------
  // Respawn handler: kills old PTY session and triggers a fresh spawn cycle
  // -------------------------------------------------------------------------
  const handleRespawn = useCallback(async () => {
    try {
      await window.api.terminal.kill(nodeId)
    } catch {
      // Already dead — that's fine
    }
    setProcessExited(false)
    setSpawnGeneration((g) => g + 1)
  }, [nodeId])

  // -------------------------------------------------------------------------
  // Debounced resize handler
  // -------------------------------------------------------------------------
  const handleResize = useCallback(() => {
    if (resizeTimerRef.current !== null) {
      clearTimeout(resizeTimerRef.current)
    }

    resizeTimerRef.current = setTimeout(() => {
      resizeTimerRef.current = null

      const fitAddon = fitAddonRef.current
      const terminal = terminalRef.current
      if (!fitAddon || !terminal || !mountedRef.current) return

      try {
        fitAddon.fit()
        const { cols, rows } = terminal
        window.api.terminal.resize(nodeId, cols, rows).catch((err: unknown) => {
          console.warn('[TerminalPanel] Resize IPC failed:', err)
        })
      } catch {
        // fit() can throw if container has zero dimensions
      }
    }, RESIZE_DEBOUNCE_MS)
  }, [nodeId])

  // -------------------------------------------------------------------------
  // Main effect: terminal lifecycle
  // -------------------------------------------------------------------------
  useEffect(() => {
    mountedRef.current = true
    const container = containerRef.current
    if (!container) return

    // --- Build theme for current mode with optional accent color override ---
    const theme = getTerminalTheme(themeMode, accentColor)

    // --- Check for reduced motion preference (accessibility) ---
    const prefersReducedMotion = window.matchMedia('(prefers-reduced-motion: reduce)').matches

    // --- Create Terminal instance ---
    const terminal = new Terminal({
      scrollback: 1000,
      fontSize: 13,
      fontFamily: "'JetBrains Mono', 'Cascadia Code', 'Consolas', 'Menlo', monospace",
      letterSpacing: 0,
      lineHeight: 1.2,
      cursorBlink: !prefersReducedMotion,
      theme,
      allowProposedApi: true,
      screenReaderMode: prefersReducedMotion,
      drawBoldTextInBrightColors: true,
      minimumContrastRatio: 1,
    })

    const fitAddon = new FitAddon()
    terminal.loadAddon(fitAddon)

    // Unicode 11: correct width calculation for box-drawing, braille, CJK, emoji
    const unicode11Addon = new Unicode11Addon()
    terminal.loadAddon(unicode11Addon)
    terminal.unicode.activeVersion = '11'

    // WebGL2 renderer: more consistent glyph rendering than canvas
    let webglAddon: WebglAddon | null = null
    try {
      webglAddon = new WebglAddon()
      webglAddon.onContextLoss(() => {
        webglAddon?.dispose()
        webglAddon = null
      })
      terminal.loadAddon(webglAddon)
    } catch {
      console.warn('[TerminalPanel] WebGL renderer not available, using canvas fallback')
    }

    terminalRef.current = terminal
    fitAddonRef.current = fitAddon

    // --- Open terminal into container ---
    terminal.open(container)

    // --- Cleanup accumulator ---
    const cleanups: Array<() => void> = []

    // --- Keyboard handler: Ctrl+` escapes terminal focus ---
    const customKeyHandler = (event: KeyboardEvent): boolean => {
      // Ctrl+` / Ctrl+~ — escape terminal focus
      if (event.ctrlKey && (event.key === '`' || event.key === '~')) {
        event.preventDefault()
        terminal.blur()
        const artboardParent = container.closest('[data-artboard]') as HTMLElement | null
        if (artboardParent) {
          artboardParent.focus()
        } else {
          ;(document.activeElement as HTMLElement | null)?.blur()
        }
        return false
      }

      // Ctrl+V / Ctrl+Shift+V / Cmd+V — clipboard paste into terminal
      const isMac = navigator.platform.includes('Mac')
      const pasteModifier = isMac ? event.metaKey : event.ctrlKey
      if (pasteModifier && event.key === 'v') {
        event.preventDefault()
        navigator.clipboard.readText().then((text) => {
          if (text && mountedRef.current) {
            // Bracket paste mode: wrap in \x1b[200~ ... \x1b[201~ so shells
            // that support it don't execute pasted newlines as commands.
            const bracketedText = `\x1b[200~${text}\x1b[201~`
            window.api.terminal.write(nodeId, bracketedText).catch((err: unknown) => {
              console.warn('[TerminalPanel] Paste write failed:', err)
            })
          }
        }).catch(() => {
          // Clipboard access denied — fall through to default xterm behavior
        })
        return false
      }

      // Ctrl+C — let xterm handle it (sends SIGINT via PTY)
      // All other keys — pass through to xterm
      return true
    }
    terminal.attachCustomKeyEventHandler(customKeyHandler)

    // --- Wire IPC listeners BEFORE spawn so no PTY data is missed ---
    const removeDataListener = window.api.terminal.onData(nodeId, (data: string) => {
      if (!mountedRef.current) return
      if (isReplayingRef.current) {
        pendingDataRef.current.push(data)
        return
      }
      if (terminalRef.current) {
        terminalRef.current.write(data)
      }
    })
    cleanups.push(removeDataListener)

    const removeExitListener = window.api.terminal.onExit(nodeId, (exitCode: number) => {
      if (mountedRef.current && terminalRef.current) {
        terminalRef.current.writeln('')
        terminalRef.current.writeln(
          `\x1b[33m[Process exited with code ${exitCode}]\x1b[0m`
        )
      }
      if (mountedRef.current) {
        setProcessExited(true)
      }
    })
    cleanups.push(removeExitListener)

    // --- Async initialization ---
    const init = async (): Promise<void> => {
      if (!mountedRef.current) return

      // 1. Fit BEFORE spawn so the PTY gets the correct dimensions from the start.
      //    Without this, terminal.cols/rows are the xterm.js defaults (80×24) and the
      //    shell's startup banner (e.g. Claude Code ASCII splash) renders at the wrong
      //    column width. FitAddon.fit() measures the container and resizes xterm.js in
      //    place; subsequent reads of terminal.cols/rows reflect the true container size.
      try {
        fitAddon.fit()
      } catch {
        // fit() can throw if the container has zero dimensions at mount time.
        // Fall through — spawn will use xterm.js defaults (80×24), which is acceptable.
      }

      if (!mountedRef.current) return

      try {
        // 2. Spawn terminal with the fitted cols/rows (main process no-ops if session
        //    already exists for nodeId, so this is safe to call on remount).
        await window.api.terminal.spawn({
          nodeId,
          sessionId,
          cols: terminal.cols,
          rows: terminal.rows,
          shell,
          nodeTitle,
          cwd,
          workspaceId: workspaceId || undefined,
        })
      } catch (err) {
        if (!mountedRef.current) return
        terminal.writeln(`\x1b[31m[Error] Failed to spawn terminal: ${err instanceof Error ? err.message : String(err)}\x1b[0m`)
        return
      }

      if (!mountedRef.current) return

      // 3. Replay scrollback — live data is buffered by the onData listener above.
      try {
        const scrollback = await window.api.terminal.getScrollback(nodeId)
        if (mountedRef.current && scrollback.length > 0) {
          for (const line of scrollback) {
            terminal.writeln(line)
          }
        }
      } catch (err) {
        console.warn('[TerminalPanel] Scrollback replay failed:', err)
      }

      if (!mountedRef.current) return

      // 4. End replay phase — flush any live data that arrived during scrollback.
      isReplayingRef.current = false
      if (pendingDataRef.current.length > 0) {
        for (const chunk of pendingDataRef.current) {
          terminal.write(chunk)
        }
        pendingDataRef.current = []
      }

      // 5. Safety resize — recalculates dimensions after PTY spawn.
      try {
        fitAddon.fit()
        await window.api.terminal.resize(nodeId, terminal.cols, terminal.rows)
      } catch {
        // Non-critical — terminal will work at default size
      }

      if (!mountedRef.current) return

      // 6. Wire user input -> PTY (after replay so user cannot type during scrollback)
      const inputDisposable = terminal.onData((data: string) => {
        window.api.terminal.write(nodeId, data).catch((err: unknown) => {
          console.warn('[TerminalPanel] Write IPC failed:', err)
        })
      })
      cleanups.push(() => inputDisposable.dispose())
    }

    init().catch((err: unknown) => {
      console.error('[TerminalPanel] Init failed:', err)
    })

    // --- ResizeObserver for container dimension changes ---
    const resizeObserver = new ResizeObserver(() => {
      handleResize()
    })
    resizeObserver.observe(container)
    cleanups.push(() => resizeObserver.disconnect())

    // --- Cleanup on unmount ---
    return () => {
      mountedRef.current = false
      isReplayingRef.current = true  // Reset for potential remount
      pendingDataRef.current = []

      // Clear any pending resize timer
      if (resizeTimerRef.current !== null) {
        clearTimeout(resizeTimerRef.current)
        resizeTimerRef.current = null
      }

      // Run all accumulated cleanups
      for (const cleanup of cleanups) {
        try {
          cleanup()
        } catch {
          // Ignore cleanup errors
        }
      }

      // Dispose xterm.js instances
      try {
        fitAddon.dispose()
      } catch {
        // Already disposed
      }
      try {
        terminal.dispose()
      } catch {
        // Already disposed
      }

      terminalRef.current = null
      fitAddonRef.current = null
    }
  }, [nodeId, sessionId, accentColor, handleResize, spawnGeneration])

  // -------------------------------------------------------------------------
  // Theme sync effect — update xterm.js colors when light/dark mode changes.
  // Separate from the main lifecycle effect to avoid dispose/recreate.
  // -------------------------------------------------------------------------
  useEffect(() => {
    const terminal = terminalRef.current
    if (!terminal) return
    // xterm.js uses reference comparison for theme objects — must use a new
    // object (spread) or the canvas repaint is skipped entirely.
    terminal.options.theme = { ...getTerminalTheme(themeMode, accentColor) }
  }, [themeMode, accentColor])

  return (
    <div
      ref={containerRef}
      className={`terminal-panel ${className ?? ''}`}
      aria-label={`Terminal for node ${nodeId}`}
      style={{
        width: '100%',
        height: '100%',
        minHeight: 120,
        position: 'relative',
        overflow: 'hidden',
        letterSpacing: 'normal',
        wordSpacing: 'normal',
        fontVariantLigatures: 'none',
        textRendering: 'auto' as const,
      }}
    >
      {/* Respawn button — visible when the PTY process has exited */}
      {processExited && (
        <button
          onClick={handleRespawn}
          style={{
            position: 'absolute',
            bottom: 28,
            right: 8,
            fontSize: 11,
            padding: '4px 10px',
            borderRadius: 4,
            background: 'var(--accent-glow, #C8963E)',
            color: '#fff',
            border: 'none',
            cursor: 'pointer',
            zIndex: 2,
            fontFamily: "'JetBrains Mono', 'Cascadia Code', 'Consolas', 'Menlo', monospace",
          }}
          aria-label="Respawn terminal"
        >
          Respawn
        </button>
      )}

      {/* Focus escape tooltip */}
      <div
        style={{
          position: 'absolute',
          bottom: 4,
          right: 8,
          fontSize: 11,
          color: TERMINAL_TOOLTIP_COLOR[themeMode],
          pointerEvents: 'none',
          zIndex: 1,
          fontFamily: "'JetBrains Mono', 'Cascadia Code', 'Consolas', 'Menlo', monospace",
          userSelect: 'none',
        }}
      >
        Ctrl+` to return to canvas
      </div>
    </div>
  )
}

export const TerminalPanel = memo(TerminalPanelInner)
TerminalPanel.displayName = 'TerminalPanel'
